/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Service
 * Authentication Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogOutRequest
 */
export interface LogOutRequest {
    /**
     * 
     * @type {number}
     * @memberof LogOutRequest
     */
    customerId?: number;
}

/**
 * Check if a given object implements the LogOutRequest interface.
 */
export function instanceOfLogOutRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LogOutRequestFromJSON(json: any): LogOutRequest {
    return LogOutRequestFromJSONTyped(json, false);
}

export function LogOutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogOutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
    };
}

export function LogOutRequestToJSON(value?: LogOutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerId': value.customerId,
    };
}

