/*
 * Price Service
 * Price Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package at.bumzack.priceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PriceEntry
 */
@JsonPropertyOrder({
  PriceEntry.JSON_PROPERTY_ID,
  PriceEntry.JSON_PROPERTY_MOVIE_TCONST,
  PriceEntry.JSON_PROPERTY_AMOUNT,
  PriceEntry.JSON_PROPERTY_CREATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-29T15:35:20.403886+02:00[Europe/Vienna]")
public class PriceEntry {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_MOVIE_TCONST = "movieTconst";
  private String movieTconst;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Double amount;

  public static final String JSON_PROPERTY_CREATED = "created";
  private LocalDateTime created;

  public PriceEntry() {
  }

  public PriceEntry id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Long id) {
    this.id = id;
  }


  public PriceEntry movieTconst(String movieTconst) {
    
    this.movieTconst = movieTconst;
    return this;
  }

   /**
   * Get movieTconst
   * @return movieTconst
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOVIE_TCONST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMovieTconst() {
    return movieTconst;
  }


  @JsonProperty(JSON_PROPERTY_MOVIE_TCONST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovieTconst(String movieTconst) {
    this.movieTconst = movieTconst;
  }


  public PriceEntry amount(Double amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(Double amount) {
    this.amount = amount;
  }


  public PriceEntry created(LocalDateTime created) {
    
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(LocalDateTime created) {
    this.created = created;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceEntry priceEntry = (PriceEntry) o;
    return Objects.equals(this.id, priceEntry.id) &&
        Objects.equals(this.movieTconst, priceEntry.movieTconst) &&
        Objects.equals(this.amount, priceEntry.amount) &&
        Objects.equals(this.created, priceEntry.created);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, movieTconst, amount, created);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceEntry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    movieTconst: ").append(toIndentedString(movieTconst)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

