/*
 * Price Service
 * Price Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package at.bumzack.priceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchPricesRequest
 */
@JsonPropertyOrder({
  SearchPricesRequest.JSON_PROPERTY_MOVIE_TCONST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-29T15:35:20.403886+02:00[Europe/Vienna]")
public class SearchPricesRequest {
  public static final String JSON_PROPERTY_MOVIE_TCONST = "movieTconst";
  private List<String> movieTconst = new ArrayList<>();

  public SearchPricesRequest() {
  }

  public SearchPricesRequest movieTconst(List<String> movieTconst) {
    
    this.movieTconst = movieTconst;
    return this;
  }

  public SearchPricesRequest addMovieTconstItem(String movieTconstItem) {
    if (this.movieTconst == null) {
      this.movieTconst = new ArrayList<>();
    }
    this.movieTconst.add(movieTconstItem);
    return this;
  }

   /**
   * Get movieTconst
   * @return movieTconst
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOVIE_TCONST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getMovieTconst() {
    return movieTconst;
  }


  @JsonProperty(JSON_PROPERTY_MOVIE_TCONST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMovieTconst(List<String> movieTconst) {
    this.movieTconst = movieTconst;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchPricesRequest searchPricesRequest = (SearchPricesRequest) o;
    return Objects.equals(this.movieTconst, searchPricesRequest.movieTconst);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movieTconst);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchPricesRequest {\n");
    sb.append("    movieTconst: ").append(toIndentedString(movieTconst)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

