/* tslint:disable */
/* eslint-disable */
/**
 * Price Service
 * Price Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 *
 * @export
 * @interface PriceEntry
 */
export interface PriceEntry {
    /**
     *
     * @type {number}
     * @memberof PriceEntry
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof PriceEntry
     */
    movieTconst?: string;
    /**
     *
     * @type {number}
     * @memberof PriceEntry
     */
    amount?: number;
    /**
     *
     * @type {Date}
     * @memberof PriceEntry
     */
    created?: Date;
}

/**
 * Check if a given object implements the PriceEntry interface.
 */
export function instanceOfPriceEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PriceEntryFromJSON(json: any): PriceEntry {
    return PriceEntryFromJSONTyped(json, false);
}

export function PriceEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'movieTconst': !exists(json, 'movieTconst') ? undefined : json['movieTconst'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
    };
}

export function PriceEntryToJSON(value?: PriceEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'movieTconst': value.movieTconst,
        'amount': value.amount,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
    };
}

