/* tslint:disable */
/* eslint-disable */
/**
 * Price Service
 * Price Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 *
 * @export
 * @interface SearchPricesRequest
 */
export interface SearchPricesRequest {
    /**
     *
     * @type {Array<string>}
     * @memberof SearchPricesRequest
     */
    movieTconst?: Array<string>;
}

/**
 * Check if a given object implements the SearchPricesRequest interface.
 */
export function instanceOfSearchPricesRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchPricesRequestFromJSON(json: any): SearchPricesRequest {
    return SearchPricesRequestFromJSONTyped(json, false);
}

export function SearchPricesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchPricesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'movieTconst': !exists(json, 'movieTconst') ? undefined : json['movieTconst'],
    };
}

export function SearchPricesRequestToJSON(value?: SearchPricesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'movieTconst': value.movieTconst,
    };
}

