server.port                =8106
server.host                =localhost
server.openapipath         =v3/api-docs
technology                 =webflux
micrsoservice.id           =solrepisodewriter
publish_as_frontend_package=false
apiclient.prefix           =SolrEpisodeWriterClient
apiclient.package          =at.bumzack.clients.solr.EpisodeWriterClient
local.repo.path            =/code/backend/webflux/v3/solrepisodewriter
#logging.level.root=DEBUG
#useful configs
# https://springdoc.org/#springdoc-openapi-core-properties
# springdoc.api-docs.path
# server.host=solrmoviewriter.webflux.foryouandyourfakewebshop.wtf


solr.host                  =localhost
solr.port                  =8984
solr.core                  =episode