name: rust-microservices
services:

  rust_tsvfilereader:
    build:
      context: datasupply/rust_tsvfilereader
    expose:
      - "18900"

  rust_crewwriter:
    build:
      context: datasupply/rust_crewwriter
    expose:
      - "80"

  rust_episodewriter:
    build:
      context: datasupply/rust_episodewriter

  rust_movieakaswriter:
    build:
      context: datasupply/rust_movieakaswriter

  rust_moviewriter:
    build:
      context: datasupply/rust_moviewriter

  rust_personwriter:
    build:
      context: datasupply/rust_personwriter

  rust_principalwriter:
    build:
      context: datasupply/rust_principalwriter

  rust_ratingwriter:
    build:
      context: datasupply/rust_ratingwriter

networks:
  client-side: {}
  server-side: {}
