# rust search services
search_movie_by_name = "http://localhost:18200/api/ENGINE/movie/"
search_movie = "http://localhost:18200/api/ENGINE/movie/"
search_person_by_nconst = "http://localhost:18203/api/ENGINE/person/nconst"
search_person = "http://localhost:18203/api/ENGINE/person/filter"
search_person_doc = "http://localhost:18203/api/v1/ENGINE/person"

search_principal_by_movie_tconst = "http://localhost:18204/api/ENGINE/principal/filter/title/"
search_principal_by_person_nconst = "http://localhost:18204/api/ENGINE/principal/filter/name/"
search_crew_by_tconst = "http://localhost:18205/api/ENGINE/crew/filter"
search_movieaka_by_tconst = "http://localhost:18201/api/ENGINE/movieaka/filter"
search_rating_by_tconst = "http://localhost:18201/api/ENGINE/rating/filter"

search_customers_paginated = "http://localhost:18980/api/v1/customer/paginated/:offset/:limit"
search_customer_by_email = "http://localhost:18980/api/v1/authentication/:email"



# logging service
loggingservice_db_user = "bumzack"
loggingservice_db_password = "bumzack"
loggingservice_db_host = "localhost"
loggingservice_db_name = "bumzack"
loggingservice_service_host = "localhost"
loggingservice_service_port = "18700"


# price service
priceservice_db_user = "bumzack"
priceservice_db_password = "bumzack"
priceservice_db_host = "localhost"
priceservice_db_name = "bumzack"
priceservice_service_host = "localhost"
priceservice_service_port = "18800"


# customer service
customerservice_db_user = "bumzack"
customerservice_db_password = "bumzack"
customerservice_db_host = "localhost"
customerservice_db_name = "bumzack"
customerservice_service_host = "localhost"
customerservice_service_port = "18980"

# customerprice service
customerpriceservice_db_user = "bumzack"
customerpriceservice_db_password = "bumzack"
customerpriceservice_db_host = "localhost"
customerpriceservice_db_name = "bumzack"
customerpriceservice_service_host = "localhost"
customerpriceservice_service_port = "18981"



# authentication service
authenticationservice_db_user = "bumzack"
authenticationservice_db_password = "bumzack"
authenticationservice_db_host = "localhost"
authenticationservice_db_name = "bumzack"
authenticationservice_service_host = "localhost"
authenticationservice_service_port = "18982"



server_port = "18900"
server_host = "127.0.0.1"
server_openapipath = "v3/api-docs"
technology = "webflux"
micrsoservice_id = "tsvfilereader"
publish_as_frontend_package = "false"
apiclient_prefix = "TsvFileReaderClient"
apiclient_package = "at.bumzack.clients.tsvfilereader"
local_repo_path = "/code/backend/webflux/v3/tsvfilereader"

datasource_folder = "/home/bumzack/micro-all-the-things/imdb_data"

datasource_MOVIE_filename = "title.basics.tsv"
datasource_MOVIEAKA_filename = "title.akas.tsv"
datasource_PERSON_filename = "name.basics.tsv"
datasource_CREW_filename = "title.crew.tsv"
datasource_EPISODE_filename = "title.episode.tsv"
datasource_PRINCIPAL_filename = "title.principals.tsv"
datasource_RATING_filename = "title.ratings.tsv"


microservice_MOVIE_host = "http://localhost"
microservice_MOVIE_port = "18100"
microservice_MOVIE_url = "/api/movie"


microservice_MOVIEAKA_host = "http://localhost"
microservice_MOVIEAKA_port = "18101"
microservice_MOVIEAKA_url = "/api/movieaka"


microservice_PERSON_host = "http://localhost"
microservice_PERSON_port = "18103"
microservice_PERSON_url = "/api/person"

microservice_CREW_host = "http://localhost"
microservice_CREW_port = "18102"
microservice_CREW_url = "/api/crew"

microservice_PRINCIPAL_host = "http://localhost"
microservice_PRINCIPAL_port = "18104"
microservice_PRINCIPAL_url = "/api/principal"

microservice_EPISODE_host = "http://localhost"
microservice_EPISODE_port = "18106"
microservice_EPISODE_url = "/api/episode"

microservice_RATING_host = "http://localhost"
microservice_RATING_port = "18105"
microservice_RATING_url = "/api/rating"

