/* tslint:disable */
/* eslint-disable */
/**
 * Search Index Index Service
 * Search Index Index Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';
import type {SearchDoc} from './SearchDoc';
import {SearchDocFromJSON, SearchDocToJSON,} from './SearchDoc';

/**
 *
 * @export
 * @interface MovieSearchResult
 */
export interface MovieSearchResult {
    /**
     *
     * @type {Array<SearchDoc>}
     * @memberof MovieSearchResult
     */
    movies?: Array<SearchDoc>;
}

/**
 * Check if a given object implements the MovieSearchResult interface.
 */
export function instanceOfMovieSearchResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieSearchResultFromJSON(json: any): MovieSearchResult {
    return MovieSearchResultFromJSONTyped(json, false);
}

export function MovieSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieSearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'movies': !exists(json, 'movies') ? undefined : ((json['movies'] as Array<any>).map(SearchDocFromJSON)),
    };
}

export function MovieSearchResultToJSON(value?: MovieSearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'movies': value.movies === undefined ? undefined : ((value.movies as Array<any>).map(SearchDocToJSON)),
    };
}

