/* tslint:disable */
/* eslint-disable */
/**
 * Search Index Index Service
 * Search Index Index Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 *
 * @export
 * @interface SearchMovieIndexRequest
 */
export interface SearchMovieIndexRequest {
    /**
     *
     * @type {string}
     * @memberof SearchMovieIndexRequest
     */
    q?: string;
    /**
     *
     * @type {number}
     * @memberof SearchMovieIndexRequest
     */
    offset?: number;
    /**
     *
     * @type {number}
     * @memberof SearchMovieIndexRequest
     */
    limit?: number;
}

/**
 * Check if a given object implements the SearchMovieIndexRequest interface.
 */
export function instanceOfSearchMovieIndexRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchMovieIndexRequestFromJSON(json: any): SearchMovieIndexRequest {
    return SearchMovieIndexRequestFromJSONTyped(json, false);
}

export function SearchMovieIndexRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMovieIndexRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'q': !exists(json, 'q') ? undefined : json['q'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
    };
}

export function SearchMovieIndexRequestToJSON(value?: SearchMovieIndexRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'q': value.q,
        'offset': value.offset,
        'limit': value.limit,
    };
}

