search_movie_by_name = "http://localhost:18200/api/movie/"
search_movie = "http://localhost:18200/api/movie/"
search_person_by_nconst = "http://localhost:18203/api/person/nconst"
search_principal_by_movie_tconst = "http://localhost:18204/api/principal/title/"
search_principal_by_person_nconst = "http://localhost:18204/api/principal/name/"
search_crew_by_tconst = "http://localhost:18205/api/crew/"



