/* tslint:disable */
/* eslint-disable */
/**
 * Search Index Index Service
 * Search Index Index Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {MovieSearchResult, SearchMovieIndexRequest,} from '../models';
import {MovieSearchResultFromJSON, SearchMovieIndexRequestToJSON,} from '../models';

export interface SearchDocsRequest {
    searchMovieIndexRequest?: SearchMovieIndexRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async searchDocsRaw(requestParameters: SearchDocsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MovieSearchResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/solr/searchindex/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchMovieIndexRequestToJSON(requestParameters.searchMovieIndexRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MovieSearchResultFromJSON(jsonValue));
    }

    /**
     */
    async searchDocs(requestParameters: SearchDocsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MovieSearchResult> {
        const response = await this.searchDocsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
