/* tslint:disable */
/* eslint-disable */
/**
 * Solr Search Article Service
 * Solr Search Article Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {SearchArticleRequest, SearchArticleResponse,} from '../models';
import {SearchArticleRequestToJSON, SearchArticleResponseFromJSON,} from '../models';

export interface SearchArticleOperationRequest {
    searchArticleRequest?: SearchArticleRequest;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async searchArticleRaw(requestParameters: SearchArticleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchArticleResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/solr/article`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchArticleRequestToJSON(requestParameters.searchArticleRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchArticleResponseFromJSON(jsonValue));
    }

    /**
     */
    async searchArticle(requestParameters: SearchArticleOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchArticleResponse> {
        const response = await this.searchArticleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
