/* tslint:disable */
/* eslint-disable */
/**
 * Customer Service
 * Customer Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 *
 * @export
 * @interface AddCustomerRequest
 */
export interface AddCustomerRequest {
    /**
     *
     * @type {string}
     * @memberof AddCustomerRequest
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof AddCustomerRequest
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof AddCustomerRequest
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof AddCustomerRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AddCustomerRequest interface.
 */
export function instanceOfAddCustomerRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddCustomerRequestFromJSON(json: any): AddCustomerRequest {
    return AddCustomerRequestFromJSONTyped(json, false);
}

export function AddCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCustomerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function AddCustomerRequestToJSON(value?: AddCustomerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'password': value.password,
    };
}

