/*
 * Price Service
 * Price Service
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package at.bumzack.priceservice.api;

import at.bumzack.priceservice.ApiClient;
import at.bumzack.priceservice.ApiException;
import at.bumzack.priceservice.ApiResponse;
import at.bumzack.priceservice.Pair;

import at.bumzack.priceservice.model.PriceEntry;
import at.bumzack.priceservice.model.SearchPricesRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-30T00:02:30.984260+02:00[Europe/Vienna]")
public class DefaultApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public DefaultApi() {
    this(new ApiClient());
  }

  public DefaultApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * 
   * 
   * @param tconst Movie tconst ID (required)
   * @return PriceEntry
   * @throws ApiException if fails to make API call
   */
  public PriceEntry getPriceForMovie(String tconst) throws ApiException {
    ApiResponse<PriceEntry> localVarResponse = getPriceForMovieWithHttpInfo(tconst);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param tconst Movie tconst ID (required)
   * @return ApiResponse&lt;PriceEntry&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PriceEntry> getPriceForMovieWithHttpInfo(String tconst) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPriceForMovieRequestBuilder(tconst);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPriceForMovie", localVarResponse);
        }
        return new ApiResponse<PriceEntry>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<PriceEntry>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPriceForMovieRequestBuilder(String tconst) throws ApiException {
    // verify the required parameter 'tconst' is set
    if (tconst == null) {
      throw new ApiException(400, "Missing the required parameter 'tconst' when calling getPriceForMovie");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/price/{tconst}"
        .replace("{tconst}", ApiClient.urlEncode(tconst.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
  /**
   * 
   * 
   * @param searchPricesRequest  (optional)
   * @return List&lt;PriceEntry&gt;
   * @throws ApiException if fails to make API call
   */
  public List<PriceEntry> getPricesForMovies(SearchPricesRequest searchPricesRequest) throws ApiException {
    ApiResponse<List<PriceEntry>> localVarResponse = getPricesForMoviesWithHttpInfo(searchPricesRequest);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param searchPricesRequest  (optional)
   * @return ApiResponse&lt;List&lt;PriceEntry&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<PriceEntry>> getPricesForMoviesWithHttpInfo(SearchPricesRequest searchPricesRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPricesForMoviesRequestBuilder(searchPricesRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPricesForMovies", localVarResponse);
        }
        return new ApiResponse<List<PriceEntry>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<PriceEntry>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPricesForMoviesRequestBuilder(SearchPricesRequest searchPricesRequest) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v2/prices";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(searchPricesRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }
}
