/* tslint:disable */
/* eslint-disable */
/**
 * Solr Search Article Service
 * Solr Search Article Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';

/**
 *
 * @export
 * @interface SearchCustomer
 */
export interface SearchCustomer {
    /**
     *
     * @type {number}
     * @memberof SearchCustomer
     */
    customerId?: number;
    /**
     *
     * @type {string}
     * @memberof SearchCustomer
     */
    jwt?: string;
}

/**
 * Check if a given object implements the SearchCustomer interface.
 */
export function instanceOfSearchCustomer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchCustomerFromJSON(json: any): SearchCustomer {
    return SearchCustomerFromJSONTyped(json, false);
}

export function SearchCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchCustomer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'customerId': !exists(json, 'customerId') ? undefined : json['customerId'],
        'jwt': !exists(json, 'jwt') ? undefined : json['jwt'],
    };
}

export function SearchCustomerToJSON(value?: SearchCustomer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'customerId': value.customerId,
        'jwt': value.jwt,
    };
}

