/* tslint:disable */
/* eslint-disable */
/**
 * Solr Search Article Service
 * Solr Search Article Service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {exists} from '../runtime';
import type {ArticleSearchResult} from './ArticleSearchResult';
import {ArticleSearchResultFromJSON, ArticleSearchResultToJSON,} from './ArticleSearchResult';

/**
 *
 * @export
 * @interface SearchArticleResponse
 */
export interface SearchArticleResponse {
    /**
     *
     * @type {Array<ArticleSearchResult>}
     * @memberof SearchArticleResponse
     */
    articles?: Array<ArticleSearchResult>;
}

/**
 * Check if a given object implements the SearchArticleResponse interface.
 */
export function instanceOfSearchArticleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SearchArticleResponseFromJSON(json: any): SearchArticleResponse {
    return SearchArticleResponseFromJSONTyped(json, false);
}

export function SearchArticleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchArticleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'articles': !exists(json, 'articles') ? undefined : ((json['articles'] as Array<any>).map(ArticleSearchResultFromJSON)),
    };
}

export function SearchArticleResponseToJSON(value?: SearchArticleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'articles': value.articles === undefined ? undefined : ((value.articles as Array<any>).map(ArticleSearchResultToJSON)),
    };
}

