version: '3.3'

services:
  ecom-mock:
    build: .
    #    network_mode: 'host'
    ports:
      - "6001:6001"
    command: [ "java", "-jar", "ecom-mock/target/ecom-mock-0.0.1-SNAPSHOT.jar" ]

  onfarming-mock:
    build: .
    #    network_mode: 'host'
    ports:
      - "6002:6002"
    command: [ "java", "-jar", "onfarming-mock/target/onfarming-mock-0.0.1-SNAPSHOT.jar" ]



